### ISSUE TITLE
Same product can be added  mulitple times in the cart.

### ISSUE THREAD

**Issue by tarunsinghdev** [tarunsinghdev/cart#1]
The app allows adding same product mulitple items to the cart.

**Comment by yogeshdecodes** [comment]
This can be solved by using local storage. We can store products by their ids in local storage and when the user again click the same product we will update quantity by +1. 

I can raise a pull request if you want. 😋

**Comment by tarunsinghdev** [comment]
How about if we can somehow detect the duplicate product being added and then instead of adding again we can simply increase the quantity of existing product.
Similar to what you said but without using local storage. I can add a check to my cart products array that if duplicate product found increase its quantity. 
Basically add a robust check to my cart array. Planning to fix this in some time. 
Thanks for your solution though much appreciated. :)

**Comment by yogeshdecodes** [comment]
Yeah, you can do that way too but I find another bug in your cart.
Steps to reproduce->
1. add product to cart 
2. remove product from cart
3. add another product to cart
4. Now it showing removed product too.

It seems you are not maintaining a global state of cart. You can use useEffect to create side effects that can solve this type of problem otherwise local storage is always the option. :)

**Comment by tarunsinghdev** [comment]
Yes I'm aware of this issue as well. Glad people are noticing. 
You can raise a separate issue for this bug.

Thanks for taking your time. I'll look into this issue as well.
Cheers. :)

**Comment by tarunsinghdev** [comment]
> Yeah, you can do that way too but I find another bug in your cart.
> Steps to reproduce->
> 
>     1. add product to cart
> 
>     2. remove product from cart
> 
>     3. add another product to cart
> 
>     4. Now it showing removed product too.
> 
> 
> It seems you are not maintaining a global state of cart. You can use useEffect to create side effects that can solve this type of problem otherwise local storage is always the option. :)

**All known bugs have now been resolved. Please feel free to raise an issue for any future bugs you find. 
Thanks for contributing.**
